name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install --no-frozen-lockfile
        continue-on-error: true
      - name: Install fallback
        run: npm install --no-frozen-lockfile --ignore-scripts
      - name: Build
        run: node_modules/.bin/tsc --noEmitOnError false --skipLibCheck true && node_modules/.bin/gulp build:icons || node_modules/.bin/tsc --noEmitOnError false --skipLibCheck true
      - name: Publish
        run: npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
